### ISSUE TITLE
Crashes and puts in safe mode

### ISSUE THREAD

**Issue by TsotsiHak** [rpetrich/ProSwitcher#116]
After the 0.7.5 upgrade, there is a crash bug. When you open an app and activate ProSwitcher while the app is loading, it crashes to safe mode. It wasn't doing this before 0.7.5

**Comment by rpetrich** [comment]
Confirmed and fixed in latest unstable

**Comment by TsotsiHak** [comment]
It's still crashing. I'm not the only one having this problem. It wasn't doing this in 0.7.3

**Comment by rpetrich** [comment]
That's because we haven't released the update yet. I can't just magically change the code running on your phone

**Comment by ghost** [comment]
Geez Ryan... You better upgrade your iPhone programming skills then ;)

**Comment by TsotsiHak** [comment]
LOL at you smart asses. I only made my first comment^^^^^because he closed the issue. LOL i like a sense of humor though.

**Comment by TsotsiHak** [comment]
0.8 no more crashing. Thanks
