### ISSUE TITLE
Mail Thumbnail Is Gone

### ISSUE THREAD

**Issue by Akhilleus70** [rpetrich/ProSwitcher#78]
After opening mail app to view new e-mails, the next time proswitcher is activated the mail thumbnail picture is gone with only its label visible, the only way to resolve this is to respring device, it doesnt re-appear by just opening mail again as it should. This is on a 3gs running 3.1.2 firmware.

**Comment by rpetrich** [comment]
Is the icon or the screenshot is missing?
Can you use Home+Sleep to generate a screenshot and post it?

**Comment by joeheathen** [comment]
Hi...I'm having the same problem, also on 3gs running 3.1.2 (jb'd with blackrain). There's something weird going on with mail in that the issue consistently arises the 4th time I minimize/switch from mail. It happens whether I use Proswitcher or the home button to "close" mail out. It's 100% reproduceable, and always on the fourth launch.

After the fourth launch,  mail continues to run okay, but I lose the screenshot in proswitcher, and mail no longer switches "gracefully". Instead of the minimizing window animation you usually get when you hit the home button, mail switches "abruptly" back to the springboard. It will stay this way until I either relaunch mail (using proswitcher) or respring. Then everything works okay for three "cycles" of switching to/away from Mail, then the weirdness starts again the 4th time I switch away from Mail (again, whther i use the home button or proswitcher).

Weird, eh?

**Comment by joeheathen** [comment]
UPDATE---- I figured it out....the culprit was intelliscreen. I figured it had to be something hooking into mail. Proswitcher just brought the issue to light. Once I disabled intelliscreen all is well. Back to lockinfo for me! Are you running intelliscreen Akhilleus?

**Comment by Akhilleus70** [comment]
Yes I am and I had suspicions it might be that, I'll uninstall intelliscreen now and see if it cures the problem, same with me it's been every 4th launch, thanks, does cydget work ok with proswitcher?

**Comment by rpetrich** [comment]
Cydget works with everything afaik

<sup>Still, we should fix the incompatibility at some point</sup>

**Comment by freakyash** [comment]
Hi, I have the issue too and can confirm it only started happening after I installed intelliscreen, a couple of weeks after first using proswitcher.

Here's an image of the bug on my iPhone 3GS 32GB. If I use the close button to quit mail then launch it again, the screenshot will appear correctly 2 or 3 times. After this the bug returns.

http://tomlow1.free.fr/temp/IMG_0019.jpg

I would be very grateful if you could help to resolve the incompatibility, or at least investigate sufficiently to conclude if its intelliscreen that needs to address the bug.

**Comment by joeheathen** [comment]
I'm pretty sure it's intelliscreen's bug. Try this: Uninstall proswitcher (and libactivator, the underlying gesture framework) and respring. With intelliscreen still installed and running, launch and quit mail 4 times. You'll notice the first three times, mail quits "gracefully" as it should, with the window minimizing and taking you back to the springboard with the animated transition. The fourth and subsequent time, however, mail quits abruptly, with no minimizing or window transition. Proswitcher only made you notice the problem because it grabs it's screenshots when apps are closing/quitting. Even without proswitcher installed, the intelliscreen bug is still there.

**Comment by freakyash** [comment]
Thanks for the reply with that useful info. Have sent off an email to Intelliscreen's support explaining the bug with links to this thread. Hopefully between their developers and possibly Proswitchers it will get fixed. It may help if anyone else who is experiencing the same bug could drop them an e-mail too?

**Comment by joeheathen** [comment]
done. I use lockinfo now instead and mail behaves fine, and their might be an even better option soon....

http://www.teehanlax.com/blog/2009/11/09/the-iphone-lock-screen-is-coming/

**Comment by The6uest** [comment]
I don't have Intelliscreen and I still have this problem with the mail thumb disappearing.
